# Generated by Django 4.2.7 on 2023-11-27 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
